sudo: required

language: minimal

services:
  - docker

env:
  global:
    - DOCKER_REPO: 9jkh/certbot-dns
    # DOCKER_USERNAME
    - secure: "ku7MYjP4x6nD0AaZEFAyvaTdQKS7oyZ3aHz/trNgUQvultSxCBQ2tZEi7mmyPvzqhxJMSnHpWZCPHTSNpiA9O4m/B8NAKIYMGynuZ8VRwlCa2TRoZ2Xqekd0Y+aiVsymamYSGJGMs0bG1TwLrowcSXHNfXR2lB44eRqwCjAGSCJFZEXDFPyLvsoBlHsDaATViVqHnT6veg6zNVldvIYM1qJ5Q+cTGB3sauy6t0lpCPQ4ys3Ixd+pYDJZR1TifNeW0Qnr+GEy6OHQW8e0ADIz8oyTLx4zk95ozWWu9QydYbValA2I8BFUjy2PW/+kGi55QoAc8t3OscH/mcK9RfuTWbsbSktDHJeUw1vk8bxTw68bljRE7TE805DnbdPcFCm4wKfSiOfpgmuAVtkBxC5i7by0dZfZX5OpBtjGzdqVn0OtPvhy15QqIv1Buhs4osrerEO3i4rLB7zDjzRzw+u5gjccnxh1PKPAuzomdg+qaZGp7HO1OPrJafaWXtLKKiTPWAJtTaoZdRuU7K5F+BXDcn6fs2Yz1XcSmDZ3eWid4LHPYOtt3X+0sTQ4K1dtiM2brpIOZUuEFXoyp/jsi34Gs/MJI9rgq4DaD7xRSQxf+mBkY/qLYhnnMHMtKTWFMMyXq+TIhugPBFgNfa9JFxJIRZZ8RJ2Wk6dw/v5I7e+cSww="
    # DOCKER_PASSWORD
    - secure: "Z79+2FhavxizscKhZjQJGIsOnVJucajN0TQL84FlCPH7Iv7hmXvZupYwoRgy5jAB65HpjJASXFsy1g6H7PJpaRCI5lmrDc9jv7DE/zDJi0C1f8iLGj5mAhn0uO5XLvEcnnQGgzOibmbd5NFvQkrEVtJvnXJgrTghN4jcns9lXlXNfmNzh0uJIzwUE22TpMFYu6d5nWtSWyPKA/mJwuzFgMGHwP/gG1jib73U/AlDoR2yi6x5nH2j+D2nwdVyKd7dcowai7nuG1l+3l6Re73s5ITX4o/AcL/odJMFmdbzwHgwogrfusg/thd0DBQhwfDIsGno23V6qCrAGo3jShYVc5NzhTDjgDGv7gArTqNuc60ZY07rcQD3wJT3i34KCm0+yjOG1N58DKur0WooXCEu5UTyjOV4S39epnZ4dk3ZACH6yHRc/zfxEaAYfGhcVQJCvbCqoRFlTm0q4hI8pHQICSnhw0qlKfx7629Gs1O6BjWQRRGsqWEoBvJ0O0r67q69MLtFATEtPDXRprnU/hW5dUHxIArK8duT8c2pPPwlEOkn6AdQ4qTEjZ5roG9ZyKoBP8zHG2WwOS1mcugftmdJl2Dj6sZbbGqe/CXcCSE7Fau03YusO6HxxubEY+M7+5AIiLiVUSdgjiQ1sn7xxVwVu/Lhzqpqts2T1IKQK70j3Ec="

before_install:
  - ./build.sh

deploy:
  provider: script
  script: "./push.sh"
  skip_cleanup: true
  on:
    branch: master
